

// TOOL:     vlog2tf
// DATE:     Mon Aug 25 17:10:05 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   LineBuffer3X3
// DESIGN:   LineBuffer3X3
// FILENAME: LineBuffer3X3_tf.v
// PROJECT:  CONV_21
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module LineBuffer3X3_tf();

// Inputs
    reg clk;
    reg rst;
    reg i_valid;
    reg [7:0] i_pixel;


// Outputs
    wire o_valid;
    wire [7:0] o_p00;
    wire [7:0] o_p01;
    wire [7:0] o_p02;
    wire [7:0] o_p10;
    wire [7:0] o_p11;
    wire [7:0] o_p12;
    wire [7:0] o_p20;
    wire [7:0] o_p21;
    wire [7:0] o_p22;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    LineBuffer3X3 UUT (
        .clk(clk), 
        .rst(rst), 
        .i_valid(i_valid), 
        .i_pixel(i_pixel), 
        .o_valid(o_valid), 
        .o_p00(o_p00), 
        .o_p01(o_p01), 
        .o_p02(o_p02), 
        .o_p10(o_p10), 
        .o_p11(o_p11), 
        .o_p12(o_p12), 
        .o_p20(o_p20), 
        .o_p21(o_p21), 
        .o_p22(o_p22)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            clk = 0;
            rst = 0;
            i_valid = 0;
            i_pixel = 0;
    end

endmodule // LineBuffer3X3_tf